# Generated by Django 4.1 on 2023-03-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_data',
            field=models.TextField(),
        ),
    ]
