# Generated by Django 4.1 on 2023-03-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_image_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_data',
        ),
    ]
