# Generated by Django 4.1 on 2023-01-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
