# Generated by Django 4.1 on 2023-01-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cartproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
